### ISSUE TITLE
在windows下fp16支持吗？推理完检测框不准确，好多重叠框

### ISSUE THREAD

**Issue by deeplearningers** [we0091234/chinese_plate_tensorrt#1]

**Comment by we0091234** [comment]
tensorrt 7吧？

**Comment by deeplearningers** [comment]
> 
是的，由于与机器其他程序同时跑，需要用tensorrt7啊，作者知道什么原因吗

**Comment by we0091234** [comment]
> > 
> 
> 是的，由于与机器其他程序同时跑，需要用tensorrt7啊，作者知道什么原因吗

tensorrt我知道啥原因了，你加群，之前有个群友，问题和你一样，最后他解决了，问一下qq群：871797331

**Comment by deeplearningers** [comment]
> > > 
> > 
> > 
> > 是的，由于与机器其他程序同时跑，需要用tensorrt7啊，作者知道什么原因吗
> 
> tensorrt我知道啥原因了，你加群，之前有个群友，问题和你一样，最后他解决了，问一下qq群：871797331

加了，哪位呢？我请教下
